const movieListConstants = {
    MOVIE_LIST_SUCCESS: 'MOVIE_LIST_SUCCESS',
    MOVIE_LIST_FAILURE: 'MOVIE_LIST_FAILURE',
    MOVIE_SEARCH_SUCCESS: "MOVIE_SEARCH_SUCCESS",
    MOVIE_SEARCH_FAILURE: "MOVIE_SEARCH_FAILURE",
    MOVIE_SEARCH_RESET: "MOVIE_SEARCH_RESET"
}

export default movieListConstants;